apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v1
  labels:
    app: appv1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appv1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      name: nginx
      labels:
        app: appv1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      