# Usamos la imagen base ngnix con la versión 1.19.3
FROM nginx:1.19.3

# Copiamos el archivo index.html que tenemos en la carpeta "html"que contiene el html personalizado en el sistema de ficheros de la 
# imagen ngnix, así sustituimos el que tiene predeterminado
COPY html/index.html /usr/share/nginx/html/


