apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset  
  namespace: practica2 
  labels: 
    app: nginx-server 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template: 
    metadata:
      name: nginx
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"