# NODE PORT

apiVersion: v1
kind: Service
metadata:
  name: node-port-servive
spec:
  type: NodePort
  selector:
    app: nginx-service
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30001