# LOAD BALANCER

apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  selector:
    app: nginx-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer